### ISSUE TITLE
Post: .github with AWL

### ISSUE THREAD

**Issue by peaceiris** [peaceiris/we-are-smarter-than-me#53]
# .githubのテンプレートをAcademic Word Listを用いて解説

## Task

- [ ] CODE_OF_CONDUCT.md
- [ ] CONTRIBUTING.md
- [ ] ISSUE_TEMPLATE.md
- [ ] PULL_REQUEST_TEMPLATE.md

## References

- https://qiita.com/nstoym/items/ca711287117074a810aa
- http://makezine.jp/blog/2017/08/project-code-conduct-contributors-yes.html
- [hugo-future-imperfect .github](https://github.com/peaceiris/hugo-future-imperfect/tree/master/.github)
